-- Добавление колонок условий работы в таблицу jobs
ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS work_schedule VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS employment_type VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS experience_level VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS education_level VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS benefits TEXT DEFAULT NULL; 